baseURL = "https://thlg057.github.io/mo5-blog/"
defaultContentLanguage = "fr"
defaultContentLanguageInSubdir = false
theme = "PaperMod"
enableRobotsTXT = true
canonifyURLs = true
pygmentsCodeFences = true
pygmentsUseClasses = true
googleAnalytics = "G-WRQSQ5Y81F"
enableRobotsTXT = true

[pagination]
  pagerSize = 10

[params]
  ShowAuthor = false
  hideFooter = true
  ShowDate = false
  copyright = "© 2025 - Projet Thomson MO5"
  #dateFormat = "02/01/2006"

[languages]
  [languages.fr]
    languageCode = "fr-fr"
    languageName = "Français"
    weight = 1
    title = "Premiers pas: Développement Thomson MO5"
    contentDir = "content/fr"
    [languages.fr.params]
      description = "Un blog rétro-computing consacré au développement sur le Thomson MO5"
    [languages.fr.params.sections.days]
      title = "Journal de développement"
      sortBy = "title"
      sortOrder = "asc"

  [languages.en]
    languageCode = "en-us"
    languageName = "English"
    weight = 2
    title = "Thomson MO5 Development: First Steps"
    contentDir = "content/en"
    [languages.en.params]
      description = "A retro-computing blog dedicated to development on the Thomson MO5"
    [languages.en.params.sections.days]
      title = "Development diary"
      sortBy = "title"
      sortOrder = "asc"

[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  term = ["HTML", "RSS"]