name: Deploy Hugo site to Pages

on:
  push:
    branches:
      - main
      - feature/blog
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Update vers v4 (plus stable)
        with:
          submodules: recursive # Assure que les thèmes sont bien récupérés
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3 # Update vers v3
        with:
          hugo-version: '0.151.0' # TA VERSION LOCALE (pour garder la compatibilité)
          extended: true

      - name: Build
        # On force la baseURL pour être sûr que les liens ne cassent pas
        run: hugo --minify --baseURL "https://thlg057.github.io/mo5-blog/"

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4 # Update vers v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          cname: thlg057.github.io
          full_commit_message: true
          force_orphan: true # Nettoie la branche gh-pages à chaque fois pour éviter les vieux fichiers fantômes